export const locale = 'fr'
export const isBigLimit = 5

export const entityNames = {
  institution: 'Institution',
  owner: 'Fournisseur',
  manager: 'Gestionnaire',
  folder: 'Dossier',
  tag: 'Mot clé',
  doc: 'Doc',
  dataset: 'Dataset',
  variable: 'Variable',
  modality: 'Modalité',
  value: 'Valeur',
  freq: 'Fréquence',
  log: 'Log',
}

export const parentEntities = {
  institution: 'parent',
  folder: 'parent',
  tag: 'parent',
  doc: 'parent',
  dataset: 'folder',
  variable: 'dataset',
  modality: 'folder',
  value: 'modality',
  freq: 'variable',
}

export const varTypes = {
  integer: 'nombre',
  float: 'décimal',
  string: 'texte',
  boolean: 'booléen',
  date: 'date',
  other: 'autre',
}

export const evolutionTypes = {
  add: 'Ajout',
  update: 'Modification',
  delete: 'Suppression',
  start_date: 'Validité début',
  end_date: 'Validité fin',
  last_update_date: 'Dernière mise à jour',
  next_update_date: 'Prochaine mise à jour',
}

export const columnCleanNames = {
  start_date: 'Validité début',
  end_date: 'Validité fin',
  last_update: 'Dernière<br>mise à jour',
  last_update_date: 'Dernière<br>mise à jour',
  next_update_date: 'Prochaine<br>mise à jour',
  name: 'Nom',
  description: 'Description',
  updating_each: 'Fréquence<br>de mise à jour',
}

export const columnIcons = {
  updating_each: 'frequency',
  last_update: 'last_update_date',
}

export const entityToIcon = {
  institution: 'university',
  owner: 'university',
  manager: 'university',
  folder: 'folder',
  tag: 'tag',
  dataset: 'table',
  variable: 'grip-lines-vertical',
  modality: 'align-left',
  value: 'ellipsis-vertical',
  doc: 'book',
  about: 'info-circle',
  favorite: 'star',
  log: 'warehouse',
  search: 'magnifying-glass',
  colSearch: 'magnifying-glass',
  recentSearch: 'clock-rotate-left',
  type: 't',
  missing: 'circle-question',
  duplicate: 'clone',
  frequency: 'calendar-alt',
  date: 'calendar-day',
  date_range: 'calendar-week',
  start_date: 'calendar-check',
  end_date: 'calendar-xmark',
  last_update_date: 'rotate-right',
  next_update_date: 'rotate-left',
  downloadFile: 'file-arrow-down',
  download: 'cloud-download-alt',
  upload: 'cloud-arrow-up',
  downloadClose: 'cloud-arrow-down fa-rotate-180',
  pdf: 'file-pdf',
  md: 'fa-brands fa-markdown',
  github: 'fa-brands fa-github',
  compare: 'object-ungroup',
  option: 'gear',
  diagram: 'diagram-project',
  email: 'envelope',
  delivery_format: 'laptop-file',
  survey_type: 'database',
  metadata_path: 'sitemap',
  level: 'layer-group',
  folder_tree: 'folder-tree',
  folder_tree_institution: 'folder-tree',
  folder_tree_folder: 'folder-tree',
  folder_tree_tag: 'folder-tree',
  git_code: 'code-branch',
  tab: 'folder-closed',
  page: 'file-lines',
  entity: 'globe',
  time_ago: 'clock',
  stat: 'signal',
  localisation: 'location-dot',
  data_path: 'server',
  name: 'signature',
  description: 'comment',
  nb_row: 'grip-lines',
  link: 'link',
  recursive: 'rotate-left',
  functionality: 'screwdriver-wrench',
  preview: 'eye',
  relation: 'arrows-left-right',
  evolution: 'history',
  add: 'plus',
  update: 'pen',
  delete: 'trash',
  internalView: 'box-open',
  internalId: 'fingerprint',
  nbSource: 'arrow-up',
  nbDerived: 'arrow-down',
  freq: 'chart-bar',
}
