import { writable, derived } from 'svelte/store'
import type { Row } from '@type'

export const page = writable('')
export const onPageHomepage = derived(page, p => p === '_index')
export const onPageSearch = derived(page, p => p === 'search')
export const pageHash = writable('')
export const headerOpen = writable(false)
export const isSmallMenu = writable(false)
export const footerVisible = writable(true)
export const pageContentLoaded = writable(false)
export const modalitiesSimilitutes = writable([])
export const nbFavorite = writable(0)
export const tabSelected = writable({ icon: '', key: '', nb: 0 })
export const allTabsIcon = writable({})
export const allTabs = writable({ stat: {} as Row })
export const allTablesLoaded = writable(false)
export const searchValue = writable('')
export const reloadIncrement = writable(0)
export const currentTabData = writable([] as Row[])
export const whenAppReady = writable<Promise<void>>(new Promise(() => {}))
