import { writable, derived } from 'svelte/store'

export const page = writable('')
export const on_page_homepage = derived(page, p => p === '_index')
export const on_page_search = derived(page, p => p === 'search')
export const page_hash = writable('')
export const header_open = writable(false)
export const is_small_menu = writable(false)
export const footer_visible = writable(true)
export const page_content_loaded = writable(false)
export const modalities_similitutes = writable([])
export const nb_favorite = writable(0)
export const tab_selected = writable({ icon: '', key: '', nb: 0 })
export const all_tabs_icon = writable({})
export const all_tabs = writable({ stat: {} as Record<string, unknown> })
export const all_tables_loaded = writable(false)
export const search_value = writable('')
export const reload_increment = writable(0)
