export const locale = "fr"

export const entity_names = {
  institution: "Institution",
  owner: "Fournisseur",
  manager: "Gestionnaire",
  folder: "Dossier",
  tag: "Mot clé",
  doc: "Doc",
  dataset: "Dataset",
  variable: "Variable",
  modality: "Modalité",
  value: "Valeur",
  log: "Log",
}

export const var_types = {
  integer: "nombre",
  float: "décimal",
  string: "texte",
  boolean: "booléen",
  date: "date",
  other: "autre",
}

export const entity_to_icon = {
  institution: "university",
  owner: "university",
  manager: "university",
  folder: "folder",
  tag: "tag",
  dataset: "table",
  variable: "grip-lines-vertical",
  modality: "align-left",
  value: "ellipsis-vertical",
  doc: "book",
  about: "info-circle",
  favorite: "star",
  log: "warehouse",
  search: "magnifying-glass",
  col_search: "magnifying-glass",
  recent_search: "clock-rotate-left",
  type: "t",
  missing: "circle-question",
  duplicate: "clone",
  frequency: "calendar-alt",
  date: "calendar-day",
  date_range: "calendar-week",
  download_file: "file-arrow-down",
  download: "cloud-download-alt",
  upload: "cloud-arrow-up",
  download_close: "cloud-arrow-down fa-rotate-180",
  pdf: "file-pdf",
  md: "fa-brands fa-markdown",
  compare: "object-ungroup",
  option: "gear",
  diagram: "diagram-project",
  email: "envelope",
  delivery_format: "laptop-file",
  survey_type: "database",
  metadata_path: "sitemap",
  entity: "object-group",
  level: "layer-group",
  folder_tree: "folder-tree",
  git_code: "code-branch",
  tab: "folder-closed",
  page: "file-lines",
  entity: "globe",
  time_ago: "clock",
  readme: "book",
  stat: "signal",
  localisation: "location-dot",
  data_path: "server",
  name: "signature",
  description: "comment",
  nb_row: "grip-lines",
  link: "link",
  recursive: "rotate-left",
}
