name: Release

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build
    
    - name: Determine release type
      id: release
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "type=stable" >> "$GITHUB_OUTPUT"
          echo "tag=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          echo "asset=datannur-app-latest.zip" >> "$GITHUB_OUTPUT"
        else
          echo "type=prerelease" >> "$GITHUB_OUTPUT"
          echo "tag=pre-release" >> "$GITHUB_OUTPUT"
          echo "asset=datannur-app-pre-release.zip" >> "$GITHUB_OUTPUT"
        fi
    
    - name: Create package
      run: cd app && zip -r "../${{ steps.release.outputs.asset }}" .
    
    - name: Delete existing pre-release
      if: steps.release.outputs.type == 'prerelease'
      run: |
        gh release delete pre-release --yes || true
        git push origin :refs/tags/pre-release || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract changelog
      id: changelog
      if: steps.release.outputs.type == 'stable'
      run: |
        VERSION="${{ steps.release.outputs.tag }}"
        VERSION="${VERSION#v}"  # Remove 'v' prefix
        
        # Extract changelog section for this version
        awk "
        /^## ${VERSION} / { found=1; next }
        /^## / && found { exit }
        found { print }
        " CHANGELOG.md > changelog_section.md
        
        # Check if changelog was found
        if [ ! -s changelog_section.md ]; then
          echo "No changelog found for version ${VERSION}"
          echo "notes=" >> "$GITHUB_OUTPUT"
        else
          echo "Changelog found for version ${VERSION}"
          # Use multiline output format
          {
            echo "notes<<EOF"
            cat changelog_section.md
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        fi

    - name: Create release
      run: |
        if [[ "${{ steps.release.outputs.type }}" == "stable" && "${{ steps.changelog.outputs.notes }}" != "" ]]; then
          # Use extracted changelog for stable releases
          gh release create "${{ steps.release.outputs.tag }}" \
            --title "datannur ${{ steps.release.outputs.tag }}" \
            --notes "${{ steps.changelog.outputs.notes }}" \
            "${{ steps.release.outputs.asset }}"
        else
          # Use auto-generated notes for prereleases or when no changelog found
          gh release create "${{ steps.release.outputs.tag }}" \
            --title "datannur ${{ steps.release.outputs.tag }}" \
            --generate-notes \
            ${{ steps.release.outputs.type == 'prerelease' && '--prerelease' || '' }} \
            "${{ steps.release.outputs.asset }}"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
